from pydantic import BaseModel
from datetime import date

class ProblemCreate(BaseModel):
    problem_name : str
    platform : str
    difficulty : str
    topic : str
    attempts : int = 1
    has_universal_pattern: bool = False
    pattern_name: str | None = None
    notes: str | None = None
    solved_date: date | None = None

class ProblemUpdate(BaseModel):
    difficulty : str | None = None
    attempts : int | None = 1
    has_universal_pattern : bool = False


class ProblemResponse(BaseModel):  # we have created it to validate the response generated by API and then send it to the client.
    problem_id : int
    problem_name : str
    platform : str
    difficulty : str
    topic : str
    attempts : int
    has_universal_pattern: bool


class ProblemsResponse(BaseModel):
    count : int
    problems : list[ProblemResponse]


class MessageResponse(BaseModel):
    message : str